---
title: "Annual Report Data Analysis - Cleaning Data"
author: "Cristin Young"
date: "2025-05-13"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---

This notebook answers study question 1 and study question 3.14.

#Read in data
```{r}
library(tidyverse)
library(janitor)
library(gt)

discharge_data <- readxl::read_xlsx("/Users/cristin/Dropbox/Rebecca and Tristan and Cristin/EInsight Data/Exports - Raw/May13_Report_Data/Dishcharge_Report.xlsx", na = c("-", "", "NA"))
demographic_data <- readxl::read_xlsx("/Users/cristin/Dropbox/Rebecca and Tristan and Cristin/EInsight Data/Exports - Raw/May13_Report_Data/Client_Demographics.xlsx", na = c("-", "", "NA"))

length(discharge_data$`Client ID`)
length(demographic_data$`Client ID`)
```

#Clean up demographic data
```{r}
#get rid of demo data
demographic_data_filtered <- demographic_data %>%
  filter(!if_any(c(`Provider ID`, `Client ID`), ~ str_detect(as.character(.x), "DEMO"))) %>% 
  clean_names()

#are there unique client IDs? 
length(unique(demographic_data_filtered$client_id)) == nrow(demographic_data_filtered)

#which IDs have been repeated and how many times? 
duplicates <- demographic_data_filtered %>% 
  group_by(client_id) %>% 
   filter(n() > 1) %>%
  tally() 

#how many rows are duplicated?
duplicates %>% 
  summarise(total_duplicated = sum(n))

#what data is repeating for each client?
demographic_data_filtered %>%
  group_by(client_id) %>%
  filter(n() > 1) %>%
  summarise(across(everything(), ~ {
    u <- unique(.x)
    if(length(u) > 1) paste(u, collapse = ", ") else NA_character_
  }), .groups = "drop") %>%
  select(client_id, where(~ any(!is.na(.))))

#for now, drop the 317 clients (1285 rows)
demographic_data_filtered <- demographic_data_filtered %>% 
  filter(!(client_id %in% duplicates$client_id))

#check again for duplicate ids, just in case
length(unique(demographic_data_filtered$client_id)) == nrow(demographic_data_filtered)
```

#Clean up discharge data
```{r}
#get rid of demo data
discharge_data_filtered <- discharge_data %>%
  filter(!if_any(c(`Provider ID`, `Client ID`), ~ str_detect(as.character(.x), "DEMO"))) %>% 
  clean_names()

#are there unique client IDs? 
length(unique(discharge_data_filtered$client_id)) == nrow(discharge_data_filtered)

#which IDs have been repeated and how many times? 
discharge_data_filtered %>% 
  group_by(client_id) %>% 
  summarise(n=n()) %>% 
  filter(n>1)

#what data is repeating for each client?
discharge_data_filtered %>%
  group_by(client_id, pre_measure_s) %>%
  filter(n() > 1) %>%
  summarise(across(everything(), ~ {
    u <- unique(.x)
    if(length(u) > 1) paste(u, collapse = ", ") else NA_character_
  }), .groups = "drop") %>%
  select(client_id, where(~ any(!is.na(.))))

unique(discharge_data_filtered$pre_measure_s)
unique(discharge_data_filtered$post_measure_s)

#clean up pre/post-measure names
discharge_data_filtered <- discharge_data_filtered %>%
  mutate(
    pre_time_point = str_extract(
      pre_measure_s, "(Initial|(?i)follow up \\d+)"),
    pre_assessment_name = str_remove(
      pre_measure_s, "(Initial|(?i)follow up \\d+)") %>% 
      str_trim()
  ) %>% 
  mutate(
    post_time_point = str_extract(
      post_measure_s, "(Initial|(?i)follow up \\d+)"),
    post_assessment_name = str_remove(
      post_measure_s, "(Initial|(?i)follow up \\d+)") %>% 
      str_trim()
  )

#see if pre/post assessment names match yet
discharge_data_filtered <- discharge_data_filtered %>% 
mutate(MatchDistinct = pre_assessment_name == post_assessment_name)

#not everyone uses the correct name for pre vs post assessment, so clean further
discharge_data_filtered <- discharge_data_filtered %>% 
  mutate(
    trimmed_pre_assessment_name = word(pre_assessment_name, 1),
    trimmed_post_assessment_name = word(post_assessment_name, 1)
  )

#are they all the same now? 
discharge_data_filtered <- discharge_data_filtered %>% 
mutate(trimmed_match = trimmed_pre_assessment_name == trimmed_post_assessment_name)

#this is the same thing - they just wrote out SDQ for post
discharge_data_filtered %>% 
  filter(trimmed_match == FALSE)
```

#Now join demographic and discharge data by client ID
```{r}
all_data <- left_join(discharge_data_filtered, demographic_data_filtered, by = c("client_id", "provider_id"))
```

#how many unique clients were served?
```{r}
n_distinct(demographic_data_filtered$client_id)
```

#how many clients had outcomes data? 
```{r}
n_distinct(all_data$client_id)
```

#write csvs
```{r}
#all data
write_csv(all_data, "/Users/cristin/Dropbox/Rebecca and Tristan and Cristin/EInsight Data/demographic_discharge_clean.csv")

#clean demo data
write_csv(demographic_data_filtered, "/Users/cristin/Dropbox/Rebecca and Tristan and Cristin/EInsight Data/demographic_data_clean.csv")

#clean dishcarge data
write_csv(discharge_data_filtered, "/Users/cristin/Dropbox/Rebecca and Tristan and Cristin/EInsight Data/discharge_data_clean.csv")
```

