---
title: "Q1.00 Clients Served"
author: "Cristin Young"
format: 
  docx:
    page-width: 7.5
editor: visual
---

## Period

2024-01-01 - 2025-12-31

## Question 1.00 clients served

**Definition:** The number of new clients served by grantees within the primary evaluation in the designated timeframe, where "served" means that a client had a new intervention start date attached to them during the designated timeframe.

**Calculation:** aggregated count of clients served by period with an intervention type and start date listed; intervention does not need to be completed; assumes dates before 2024 are correct and any rows with these dates have not been revised

**Assumptions:** This is discharge data from EInsight, so can have clients in here multiple times (they can have multiple interventions, or the same intervention on multiple dates). I filtered out dates before 2024-01-01, and did not clean dates at all.

```{r client_serve}
#| echo: false
#| warning: false
#| message: false
library(readr)
library(tidyverse)
library(janitor)
library(openxlsx)

discharge_data_filtered <- read_csv("/Users/cristin/CWS Dropbox/Cristin Young/CYBHI Project/Rebecca and Tristan and Cristin/EInsight Data/discharge_data_clean.csv")
discharge_data_filtered$intervention_start_year <- year(discharge_data_filtered$intervention_start)
discharge_data_filtered <- discharge_data_filtered |> 
  filter(!is.na(intervention_start), # has to have an intervention start date
         !is.na(intervention_name)) # has to have an intervention type named

client_serve <- discharge_data_filtered |> 
  filter(intervention_start >= "2024-01-01",
         intervention_start <= "2025-12-31") |>
    tabyl(intervention_start_year)
client_serve 

openxlsx::write.xlsx(client_serve,"/Users/cristin/CWS Dropbox/Cristin Young/CYBHI Project/Rebecca and Tristan and Cristin/Annual Report Development/Results Tables/Client_serve.xlsx")
```

