---
title: "Annual Report Data Analysis - Question 4.02"
author: "Tristan Burgess and Cristin Young"
date: "`r Sys.Date()`"
output:
  html_document:
    self-contained: true
    df_print: paged
editor_options:
  chunk_output_type: inline
  markdown:
    wrap: 72
---

# 4. What percentage of clients reported high satisfaction with services?

```{r setup}
#| echo: false
#| warning: false
#| message: false
library(tidyverse)
library(janitor)
library(ggridges)
library(scales)
```

```{r load_data}
#| echo: false
#| warning: false
#| message: false
assess_dir <- "/Users/cristin/CWS Dropbox/Cristin Young/CYBHI Project/Rebecca and Tristan and Cristin/EInsight Data"

# Produced by data cleaning/satisfaction_data_cleaning.qmd
sat_combined <- read_csv(
  file.path(assess_dir, "combined_satisfaction_clean.csv"),
  show_col_types = FALSE
) |>
  filter(
    !is.na(date_clean)
  ) |>
  mutate(quarter_label = factor(quarter_label, levels = unique(quarter_label)))
```

## 4.02 What, if any, factors predicted high satisfaction with services ratings by clients?

**Definition:** 

**Calculation:** 

**Assumptions:** 

**Final analysis:** Regression - outcomes = high satisfaction (4/5 vs other). Same predictors as for 3.01
